# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _edsdk
else:
    import _edsdk

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


kEdsDataType_Unknown = _edsdk.kEdsDataType_Unknown
kEdsDataType_Bool = _edsdk.kEdsDataType_Bool
kEdsDataType_String = _edsdk.kEdsDataType_String
kEdsDataType_Int8 = _edsdk.kEdsDataType_Int8
kEdsDataType_UInt8 = _edsdk.kEdsDataType_UInt8
kEdsDataType_Int16 = _edsdk.kEdsDataType_Int16
kEdsDataType_UInt16 = _edsdk.kEdsDataType_UInt16
kEdsDataType_Int32 = _edsdk.kEdsDataType_Int32
kEdsDataType_UInt32 = _edsdk.kEdsDataType_UInt32
kEdsDataType_Int64 = _edsdk.kEdsDataType_Int64
kEdsDataType_UInt64 = _edsdk.kEdsDataType_UInt64
kEdsDataType_Float = _edsdk.kEdsDataType_Float
kEdsDataType_Double = _edsdk.kEdsDataType_Double
kEdsDataType_ByteBlock = _edsdk.kEdsDataType_ByteBlock
kEdsDataType_Rational = _edsdk.kEdsDataType_Rational
kEdsDataType_Point = _edsdk.kEdsDataType_Point
kEdsDataType_Rect = _edsdk.kEdsDataType_Rect
kEdsDataType_Time = _edsdk.kEdsDataType_Time
kEdsDataType_Bool_Array = _edsdk.kEdsDataType_Bool_Array
kEdsDataType_Int8_Array = _edsdk.kEdsDataType_Int8_Array
kEdsDataType_Int16_Array = _edsdk.kEdsDataType_Int16_Array
kEdsDataType_Int32_Array = _edsdk.kEdsDataType_Int32_Array
kEdsDataType_UInt8_Array = _edsdk.kEdsDataType_UInt8_Array
kEdsDataType_UInt16_Array = _edsdk.kEdsDataType_UInt16_Array
kEdsDataType_UInt32_Array = _edsdk.kEdsDataType_UInt32_Array
kEdsDataType_Rational_Array = _edsdk.kEdsDataType_Rational_Array
kEdsDataType_FocusInfo = _edsdk.kEdsDataType_FocusInfo
kEdsDataType_PictureStyleDesc = _edsdk.kEdsDataType_PictureStyleDesc
kEdsCameraCommand_EvfAf_OFF = _edsdk.kEdsCameraCommand_EvfAf_OFF
kEdsCameraCommand_EvfAf_ON = _edsdk.kEdsCameraCommand_EvfAf_ON
kEdsCameraCommand_ShutterButton_OFF = _edsdk.kEdsCameraCommand_ShutterButton_OFF
kEdsCameraCommand_ShutterButton_Halfway = _edsdk.kEdsCameraCommand_ShutterButton_Halfway
kEdsCameraCommand_ShutterButton_Completely = _edsdk.kEdsCameraCommand_ShutterButton_Completely
kEdsCameraCommand_ShutterButton_Halfway_NonAF = _edsdk.kEdsCameraCommand_ShutterButton_Halfway_NonAF
kEdsCameraCommand_ShutterButton_Completely_NonAF = _edsdk.kEdsCameraCommand_ShutterButton_Completely_NonAF
kEdsEvfDriveLens_Near1 = _edsdk.kEdsEvfDriveLens_Near1
kEdsEvfDriveLens_Near2 = _edsdk.kEdsEvfDriveLens_Near2
kEdsEvfDriveLens_Near3 = _edsdk.kEdsEvfDriveLens_Near3
kEdsEvfDriveLens_Far1 = _edsdk.kEdsEvfDriveLens_Far1
kEdsEvfDriveLens_Far2 = _edsdk.kEdsEvfDriveLens_Far2
kEdsEvfDriveLens_Far3 = _edsdk.kEdsEvfDriveLens_Far3
kEdsDrivePowerZoom_Stop = _edsdk.kEdsDrivePowerZoom_Stop
kEdsDrivePowerZoom_LimitOff_Wide = _edsdk.kEdsDrivePowerZoom_LimitOff_Wide
kEdsDrivePowerZoom_LimitOff_Tele = _edsdk.kEdsDrivePowerZoom_LimitOff_Tele
kEdsDrivePowerZoom_LimitOn_Wide = _edsdk.kEdsDrivePowerZoom_LimitOn_Wide
kEdsDrivePowerZoom_LimitOn_Tele = _edsdk.kEdsDrivePowerZoom_LimitOn_Tele
kEdsEvfDepthOfFieldPreview_OFF = _edsdk.kEdsEvfDepthOfFieldPreview_OFF
kEdsEvfDepthOfFieldPreview_ON = _edsdk.kEdsEvfDepthOfFieldPreview_ON
kEdsSeek_Cur = _edsdk.kEdsSeek_Cur
kEdsSeek_Begin = _edsdk.kEdsSeek_Begin
kEdsSeek_End = _edsdk.kEdsSeek_End
kEdsAccess_Read = _edsdk.kEdsAccess_Read
kEdsAccess_Write = _edsdk.kEdsAccess_Write
kEdsAccess_ReadWrite = _edsdk.kEdsAccess_ReadWrite
kEdsAccess_Error = _edsdk.kEdsAccess_Error
kEdsFileCreateDisposition_CreateNew = _edsdk.kEdsFileCreateDisposition_CreateNew
kEdsFileCreateDisposition_CreateAlways = _edsdk.kEdsFileCreateDisposition_CreateAlways
kEdsFileCreateDisposition_OpenExisting = _edsdk.kEdsFileCreateDisposition_OpenExisting
kEdsFileCreateDisposition_OpenAlways = _edsdk.kEdsFileCreateDisposition_OpenAlways
kEdsFileCreateDisposition_TruncateExsisting = _edsdk.kEdsFileCreateDisposition_TruncateExsisting
kEdsImageType_Unknown = _edsdk.kEdsImageType_Unknown
kEdsImageType_Jpeg = _edsdk.kEdsImageType_Jpeg
kEdsImageType_CRW = _edsdk.kEdsImageType_CRW
kEdsImageType_RAW = _edsdk.kEdsImageType_RAW
kEdsImageType_CR2 = _edsdk.kEdsImageType_CR2
kEdsImageType_HEIF = _edsdk.kEdsImageType_HEIF
kEdsImageSize_Large = _edsdk.kEdsImageSize_Large
kEdsImageSize_Middle = _edsdk.kEdsImageSize_Middle
kEdsImageSize_Small = _edsdk.kEdsImageSize_Small
kEdsImageSize_Middle1 = _edsdk.kEdsImageSize_Middle1
kEdsImageSize_Middle2 = _edsdk.kEdsImageSize_Middle2
kEdsImageSize_Small1 = _edsdk.kEdsImageSize_Small1
kEdsImageSize_Small2 = _edsdk.kEdsImageSize_Small2
kEdsImageSize_Small3 = _edsdk.kEdsImageSize_Small3
kEdsImageSize_Unknown = _edsdk.kEdsImageSize_Unknown
kEdsCompressQuality_Normal = _edsdk.kEdsCompressQuality_Normal
kEdsCompressQuality_Fine = _edsdk.kEdsCompressQuality_Fine
kEdsCompressQuality_Lossless = _edsdk.kEdsCompressQuality_Lossless
kEdsCompressQuality_SuperFine = _edsdk.kEdsCompressQuality_SuperFine
kEdsCompressQuality_Unknown = _edsdk.kEdsCompressQuality_Unknown
EdsImageQuality_LJ = _edsdk.EdsImageQuality_LJ
EdsImageQuality_MJ = _edsdk.EdsImageQuality_MJ
EdsImageQuality_M1J = _edsdk.EdsImageQuality_M1J
EdsImageQuality_M1F = _edsdk.EdsImageQuality_M1F
EdsImageQuality_M1N = _edsdk.EdsImageQuality_M1N
EdsImageQuality_M2J = _edsdk.EdsImageQuality_M2J
EdsImageQuality_M2F = _edsdk.EdsImageQuality_M2F
EdsImageQuality_M2N = _edsdk.EdsImageQuality_M2N
EdsImageQuality_SJ = _edsdk.EdsImageQuality_SJ
EdsImageQuality_S1J = _edsdk.EdsImageQuality_S1J
EdsImageQuality_S2J = _edsdk.EdsImageQuality_S2J
EdsImageQuality_LJF = _edsdk.EdsImageQuality_LJF
EdsImageQuality_LJN = _edsdk.EdsImageQuality_LJN
EdsImageQuality_MJF = _edsdk.EdsImageQuality_MJF
EdsImageQuality_MJN = _edsdk.EdsImageQuality_MJN
EdsImageQuality_SJF = _edsdk.EdsImageQuality_SJF
EdsImageQuality_SJN = _edsdk.EdsImageQuality_SJN
EdsImageQuality_S1JF = _edsdk.EdsImageQuality_S1JF
EdsImageQuality_S1JN = _edsdk.EdsImageQuality_S1JN
EdsImageQuality_S2JF = _edsdk.EdsImageQuality_S2JF
EdsImageQuality_S3JF = _edsdk.EdsImageQuality_S3JF
EdsImageQuality_LR = _edsdk.EdsImageQuality_LR
EdsImageQuality_LRLJF = _edsdk.EdsImageQuality_LRLJF
EdsImageQuality_LRLJN = _edsdk.EdsImageQuality_LRLJN
EdsImageQuality_LRMJF = _edsdk.EdsImageQuality_LRMJF
EdsImageQuality_LRMJN = _edsdk.EdsImageQuality_LRMJN
EdsImageQuality_LRSJF = _edsdk.EdsImageQuality_LRSJF
EdsImageQuality_LRSJN = _edsdk.EdsImageQuality_LRSJN
EdsImageQuality_LRS1JF = _edsdk.EdsImageQuality_LRS1JF
EdsImageQuality_LRS1JN = _edsdk.EdsImageQuality_LRS1JN
EdsImageQuality_LRS2JF = _edsdk.EdsImageQuality_LRS2JF
EdsImageQuality_LRS3JF = _edsdk.EdsImageQuality_LRS3JF
EdsImageQuality_LRLJ = _edsdk.EdsImageQuality_LRLJ
EdsImageQuality_LRMJ = _edsdk.EdsImageQuality_LRMJ
EdsImageQuality_LRM1J = _edsdk.EdsImageQuality_LRM1J
EdsImageQuality_LRM1F = _edsdk.EdsImageQuality_LRM1F
EdsImageQuality_LRM1N = _edsdk.EdsImageQuality_LRM1N
EdsImageQuality_LRM2J = _edsdk.EdsImageQuality_LRM2J
EdsImageQuality_LRM2F = _edsdk.EdsImageQuality_LRM2F
EdsImageQuality_LRM2N = _edsdk.EdsImageQuality_LRM2N
EdsImageQuality_LRSJ = _edsdk.EdsImageQuality_LRSJ
EdsImageQuality_LRS1J = _edsdk.EdsImageQuality_LRS1J
EdsImageQuality_LRS2J = _edsdk.EdsImageQuality_LRS2J
EdsImageQuality_MR = _edsdk.EdsImageQuality_MR
EdsImageQuality_MRLJF = _edsdk.EdsImageQuality_MRLJF
EdsImageQuality_MRLJN = _edsdk.EdsImageQuality_MRLJN
EdsImageQuality_MRMJF = _edsdk.EdsImageQuality_MRMJF
EdsImageQuality_MRMJN = _edsdk.EdsImageQuality_MRMJN
EdsImageQuality_MRSJF = _edsdk.EdsImageQuality_MRSJF
EdsImageQuality_MRSJN = _edsdk.EdsImageQuality_MRSJN
EdsImageQuality_MRS1JF = _edsdk.EdsImageQuality_MRS1JF
EdsImageQuality_MRS1JN = _edsdk.EdsImageQuality_MRS1JN
EdsImageQuality_MRS2JF = _edsdk.EdsImageQuality_MRS2JF
EdsImageQuality_MRS3JF = _edsdk.EdsImageQuality_MRS3JF
EdsImageQuality_MRLJ = _edsdk.EdsImageQuality_MRLJ
EdsImageQuality_MRM1J = _edsdk.EdsImageQuality_MRM1J
EdsImageQuality_MRM1F = _edsdk.EdsImageQuality_MRM1F
EdsImageQuality_MRM1N = _edsdk.EdsImageQuality_MRM1N
EdsImageQuality_MRM2J = _edsdk.EdsImageQuality_MRM2J
EdsImageQuality_MRM2F = _edsdk.EdsImageQuality_MRM2F
EdsImageQuality_MRM2N = _edsdk.EdsImageQuality_MRM2N
EdsImageQuality_MRSJ = _edsdk.EdsImageQuality_MRSJ
EdsImageQuality_SR = _edsdk.EdsImageQuality_SR
EdsImageQuality_SRLJF = _edsdk.EdsImageQuality_SRLJF
EdsImageQuality_SRLJN = _edsdk.EdsImageQuality_SRLJN
EdsImageQuality_SRMJF = _edsdk.EdsImageQuality_SRMJF
EdsImageQuality_SRMJN = _edsdk.EdsImageQuality_SRMJN
EdsImageQuality_SRSJF = _edsdk.EdsImageQuality_SRSJF
EdsImageQuality_SRSJN = _edsdk.EdsImageQuality_SRSJN
EdsImageQuality_SRS1JF = _edsdk.EdsImageQuality_SRS1JF
EdsImageQuality_SRS1JN = _edsdk.EdsImageQuality_SRS1JN
EdsImageQuality_SRS2JF = _edsdk.EdsImageQuality_SRS2JF
EdsImageQuality_SRS3JF = _edsdk.EdsImageQuality_SRS3JF
EdsImageQuality_SRLJ = _edsdk.EdsImageQuality_SRLJ
EdsImageQuality_SRM1J = _edsdk.EdsImageQuality_SRM1J
EdsImageQuality_SRM1F = _edsdk.EdsImageQuality_SRM1F
EdsImageQuality_SRM1N = _edsdk.EdsImageQuality_SRM1N
EdsImageQuality_SRM2J = _edsdk.EdsImageQuality_SRM2J
EdsImageQuality_SRM2F = _edsdk.EdsImageQuality_SRM2F
EdsImageQuality_SRM2N = _edsdk.EdsImageQuality_SRM2N
EdsImageQuality_SRSJ = _edsdk.EdsImageQuality_SRSJ
EdsImageQuality_CR = _edsdk.EdsImageQuality_CR
EdsImageQuality_CRLJF = _edsdk.EdsImageQuality_CRLJF
EdsImageQuality_CRMJF = _edsdk.EdsImageQuality_CRMJF
EdsImageQuality_CRM1JF = _edsdk.EdsImageQuality_CRM1JF
EdsImageQuality_CRM2JF = _edsdk.EdsImageQuality_CRM2JF
EdsImageQuality_CRSJF = _edsdk.EdsImageQuality_CRSJF
EdsImageQuality_CRS1JF = _edsdk.EdsImageQuality_CRS1JF
EdsImageQuality_CRS2JF = _edsdk.EdsImageQuality_CRS2JF
EdsImageQuality_CRS3JF = _edsdk.EdsImageQuality_CRS3JF
EdsImageQuality_CRLJN = _edsdk.EdsImageQuality_CRLJN
EdsImageQuality_CRMJN = _edsdk.EdsImageQuality_CRMJN
EdsImageQuality_CRM1JN = _edsdk.EdsImageQuality_CRM1JN
EdsImageQuality_CRM2JN = _edsdk.EdsImageQuality_CRM2JN
EdsImageQuality_CRSJN = _edsdk.EdsImageQuality_CRSJN
EdsImageQuality_CRS1JN = _edsdk.EdsImageQuality_CRS1JN
EdsImageQuality_CRLJ = _edsdk.EdsImageQuality_CRLJ
EdsImageQuality_CRMJ = _edsdk.EdsImageQuality_CRMJ
EdsImageQuality_CRM1J = _edsdk.EdsImageQuality_CRM1J
EdsImageQuality_CRM2J = _edsdk.EdsImageQuality_CRM2J
EdsImageQuality_CRSJ = _edsdk.EdsImageQuality_CRSJ
EdsImageQuality_CRS1J = _edsdk.EdsImageQuality_CRS1J
EdsImageQuality_CRS2J = _edsdk.EdsImageQuality_CRS2J
EdsImageQuality_HEIFL = _edsdk.EdsImageQuality_HEIFL
EdsImageQuality_HEIFM = _edsdk.EdsImageQuality_HEIFM
EdsImageQuality_HEIFM1 = _edsdk.EdsImageQuality_HEIFM1
EdsImageQuality_HEIFM2 = _edsdk.EdsImageQuality_HEIFM2
EdsImageQuality_HEIFLF = _edsdk.EdsImageQuality_HEIFLF
EdsImageQuality_HEIFLN = _edsdk.EdsImageQuality_HEIFLN
EdsImageQuality_HEIFMF = _edsdk.EdsImageQuality_HEIFMF
EdsImageQuality_HEIFMN = _edsdk.EdsImageQuality_HEIFMN
EdsImageQuality_HEIFS1 = _edsdk.EdsImageQuality_HEIFS1
EdsImageQuality_HEIFS1F = _edsdk.EdsImageQuality_HEIFS1F
EdsImageQuality_HEIFS1N = _edsdk.EdsImageQuality_HEIFS1N
EdsImageQuality_HEIFS2 = _edsdk.EdsImageQuality_HEIFS2
EdsImageQuality_HEIFS2F = _edsdk.EdsImageQuality_HEIFS2F
EdsImageQuality_RHEIFL = _edsdk.EdsImageQuality_RHEIFL
EdsImageQuality_RHEIFLF = _edsdk.EdsImageQuality_RHEIFLF
EdsImageQuality_RHEIFLN = _edsdk.EdsImageQuality_RHEIFLN
EdsImageQuality_RHEIFM = _edsdk.EdsImageQuality_RHEIFM
EdsImageQuality_RHEIFM1 = _edsdk.EdsImageQuality_RHEIFM1
EdsImageQuality_RHEIFM2 = _edsdk.EdsImageQuality_RHEIFM2
EdsImageQuality_RHEIFMF = _edsdk.EdsImageQuality_RHEIFMF
EdsImageQuality_RHEIFMN = _edsdk.EdsImageQuality_RHEIFMN
EdsImageQuality_RHEIFS1 = _edsdk.EdsImageQuality_RHEIFS1
EdsImageQuality_RHEIFS1F = _edsdk.EdsImageQuality_RHEIFS1F
EdsImageQuality_RHEIFS1N = _edsdk.EdsImageQuality_RHEIFS1N
EdsImageQuality_RHEIFS2 = _edsdk.EdsImageQuality_RHEIFS2
EdsImageQuality_RHEIFS2F = _edsdk.EdsImageQuality_RHEIFS2F
EdsImageQuality_CRHEIFL = _edsdk.EdsImageQuality_CRHEIFL
EdsImageQuality_CRHEIFLF = _edsdk.EdsImageQuality_CRHEIFLF
EdsImageQuality_CRHEIFLN = _edsdk.EdsImageQuality_CRHEIFLN
EdsImageQuality_CRHEIFM = _edsdk.EdsImageQuality_CRHEIFM
EdsImageQuality_CRHEIFMF = _edsdk.EdsImageQuality_CRHEIFMF
EdsImageQuality_CRHEIFMN = _edsdk.EdsImageQuality_CRHEIFMN
EdsImageQuality_CRHEIFM1 = _edsdk.EdsImageQuality_CRHEIFM1
EdsImageQuality_CRHEIFM2 = _edsdk.EdsImageQuality_CRHEIFM2
EdsImageQuality_CRHEIFS1 = _edsdk.EdsImageQuality_CRHEIFS1
EdsImageQuality_CRHEIFS1F = _edsdk.EdsImageQuality_CRHEIFS1F
EdsImageQuality_CRHEIFS1N = _edsdk.EdsImageQuality_CRHEIFS1N
EdsImageQuality_CRHEIFS2 = _edsdk.EdsImageQuality_CRHEIFS2
EdsImageQuality_CRHEIFS2F = _edsdk.EdsImageQuality_CRHEIFS2F
EdsImageQuality_Unknown = _edsdk.EdsImageQuality_Unknown
kEdsImageSrc_FullView = _edsdk.kEdsImageSrc_FullView
kEdsImageSrc_Thumbnail = _edsdk.kEdsImageSrc_Thumbnail
kEdsImageSrc_Preview = _edsdk.kEdsImageSrc_Preview
kEdsImageSrc_RAWThumbnail = _edsdk.kEdsImageSrc_RAWThumbnail
kEdsImageSrc_RAWFullView = _edsdk.kEdsImageSrc_RAWFullView
kEdsTargetImageType_Unknown = _edsdk.kEdsTargetImageType_Unknown
kEdsTargetImageType_Jpeg = _edsdk.kEdsTargetImageType_Jpeg
kEdsTargetImageType_TIFF = _edsdk.kEdsTargetImageType_TIFF
kEdsTargetImageType_TIFF16 = _edsdk.kEdsTargetImageType_TIFF16
kEdsTargetImageType_RGB = _edsdk.kEdsTargetImageType_RGB
kEdsTargetImageType_RGB16 = _edsdk.kEdsTargetImageType_RGB16
kEdsTargetImageType_DIB = _edsdk.kEdsTargetImageType_DIB
kEdsProgressOption_NoReport = _edsdk.kEdsProgressOption_NoReport
kEdsProgressOption_Done = _edsdk.kEdsProgressOption_Done
kEdsProgressOption_Periodically = _edsdk.kEdsProgressOption_Periodically
kEdsFileAttribute_Normal = _edsdk.kEdsFileAttribute_Normal
kEdsFileAttribute_ReadOnly = _edsdk.kEdsFileAttribute_ReadOnly
kEdsFileAttribute_Hidden = _edsdk.kEdsFileAttribute_Hidden
kEdsFileAttribute_System = _edsdk.kEdsFileAttribute_System
kEdsFileAttribute_Archive = _edsdk.kEdsFileAttribute_Archive
kEdsObjectFormat_Unknown = _edsdk.kEdsObjectFormat_Unknown
kEdsObjectFormat_Jpeg = _edsdk.kEdsObjectFormat_Jpeg
kEdsObjectFormat_CR2 = _edsdk.kEdsObjectFormat_CR2
kEdsObjectFormat_MP4 = _edsdk.kEdsObjectFormat_MP4
kEdsObjectFormat_CR3 = _edsdk.kEdsObjectFormat_CR3
kEdsObjectFormat_HEIF_CODE = _edsdk.kEdsObjectFormat_HEIF_CODE
kEdsBatteryLevel2_Empty = _edsdk.kEdsBatteryLevel2_Empty
kEdsBatteryLevel2_Low = _edsdk.kEdsBatteryLevel2_Low
kEdsBatteryLevel2_Half = _edsdk.kEdsBatteryLevel2_Half
kEdsBatteryLevel2_Normal = _edsdk.kEdsBatteryLevel2_Normal
kEdsBatteryLevel2_Hi = _edsdk.kEdsBatteryLevel2_Hi
kEdsBatteryLevel2_Quarter = _edsdk.kEdsBatteryLevel2_Quarter
kEdsBatteryLevel2_Error = _edsdk.kEdsBatteryLevel2_Error
kEdsBatteryLevel2_BCLevel = _edsdk.kEdsBatteryLevel2_BCLevel
kEdsBatteryLevel2_AC = _edsdk.kEdsBatteryLevel2_AC
kEdsBatteryLevel2_Unknown = _edsdk.kEdsBatteryLevel2_Unknown
kEdsSaveTo_Camera = _edsdk.kEdsSaveTo_Camera
kEdsSaveTo_Host = _edsdk.kEdsSaveTo_Host
kEdsSaveTo_Both = _edsdk.kEdsSaveTo_Both
kEdsStorageType_Non = _edsdk.kEdsStorageType_Non
kEdsStorageType_CF = _edsdk.kEdsStorageType_CF
kEdsStorageType_SD = _edsdk.kEdsStorageType_SD
kEdsStorageType_HD = _edsdk.kEdsStorageType_HD
kEdsStorageType_CFast = _edsdk.kEdsStorageType_CFast
kEdsStorageType_CFe = _edsdk.kEdsStorageType_CFe
kEdsWhiteBalance_Auto = _edsdk.kEdsWhiteBalance_Auto
kEdsWhiteBalance_Daylight = _edsdk.kEdsWhiteBalance_Daylight
kEdsWhiteBalance_Cloudy = _edsdk.kEdsWhiteBalance_Cloudy
kEdsWhiteBalance_Tungsten = _edsdk.kEdsWhiteBalance_Tungsten
kEdsWhiteBalance_Fluorescent = _edsdk.kEdsWhiteBalance_Fluorescent
kEdsWhiteBalance_Strobe = _edsdk.kEdsWhiteBalance_Strobe
kEdsWhiteBalance_WhitePaper = _edsdk.kEdsWhiteBalance_WhitePaper
kEdsWhiteBalance_Shade = _edsdk.kEdsWhiteBalance_Shade
kEdsWhiteBalance_ColorTemp = _edsdk.kEdsWhiteBalance_ColorTemp
kEdsWhiteBalance_PCSet1 = _edsdk.kEdsWhiteBalance_PCSet1
kEdsWhiteBalance_PCSet2 = _edsdk.kEdsWhiteBalance_PCSet2
kEdsWhiteBalance_PCSet3 = _edsdk.kEdsWhiteBalance_PCSet3
kEdsWhiteBalance_WhitePaper2 = _edsdk.kEdsWhiteBalance_WhitePaper2
kEdsWhiteBalance_WhitePaper3 = _edsdk.kEdsWhiteBalance_WhitePaper3
kEdsWhiteBalance_WhitePaper4 = _edsdk.kEdsWhiteBalance_WhitePaper4
kEdsWhiteBalance_WhitePaper5 = _edsdk.kEdsWhiteBalance_WhitePaper5
kEdsWhiteBalance_PCSet4 = _edsdk.kEdsWhiteBalance_PCSet4
kEdsWhiteBalance_PCSet5 = _edsdk.kEdsWhiteBalance_PCSet5
kEdsWhiteBalance_AwbWhite = _edsdk.kEdsWhiteBalance_AwbWhite
kEdsWhiteBalance_Click = _edsdk.kEdsWhiteBalance_Click
kEdsWhiteBalance_Pasted = _edsdk.kEdsWhiteBalance_Pasted
kEdsColorSpace_sRGB = _edsdk.kEdsColorSpace_sRGB
kEdsColorSpace_AdobeRGB = _edsdk.kEdsColorSpace_AdobeRGB
kEdsColorSpace_Unknown = _edsdk.kEdsColorSpace_Unknown
kEdsPictureStyle_Standard = _edsdk.kEdsPictureStyle_Standard
kEdsPictureStyle_Portrait = _edsdk.kEdsPictureStyle_Portrait
kEdsPictureStyle_Landscape = _edsdk.kEdsPictureStyle_Landscape
kEdsPictureStyle_Neutral = _edsdk.kEdsPictureStyle_Neutral
kEdsPictureStyle_Faithful = _edsdk.kEdsPictureStyle_Faithful
kEdsPictureStyle_Monochrome = _edsdk.kEdsPictureStyle_Monochrome
kEdsPictureStyle_Auto = _edsdk.kEdsPictureStyle_Auto
kEdsPictureStyle_FineDetail = _edsdk.kEdsPictureStyle_FineDetail
kEdsPictureStyle_User1 = _edsdk.kEdsPictureStyle_User1
kEdsPictureStyle_User2 = _edsdk.kEdsPictureStyle_User2
kEdsPictureStyle_User3 = _edsdk.kEdsPictureStyle_User3
kEdsPictureStyle_PC1 = _edsdk.kEdsPictureStyle_PC1
kEdsPictureStyle_PC2 = _edsdk.kEdsPictureStyle_PC2
kEdsPictureStyle_PC3 = _edsdk.kEdsPictureStyle_PC3
kEdsTransferOption_ByDirectTransfer = _edsdk.kEdsTransferOption_ByDirectTransfer
kEdsTransferOption_ByRelease = _edsdk.kEdsTransferOption_ByRelease
kEdsTransferOption_ToDesktop = _edsdk.kEdsTransferOption_ToDesktop
kEdsAEMode_Program = _edsdk.kEdsAEMode_Program
kEdsAEMode_Tv = _edsdk.kEdsAEMode_Tv
kEdsAEMode_Av = _edsdk.kEdsAEMode_Av
kEdsAEMode_Manual = _edsdk.kEdsAEMode_Manual
kEdsAEMode_Bulb = _edsdk.kEdsAEMode_Bulb
kEdsAEMode_A_DEP = _edsdk.kEdsAEMode_A_DEP
kEdsAEMode_DEP = _edsdk.kEdsAEMode_DEP
kEdsAEMode_Custom = _edsdk.kEdsAEMode_Custom
kEdsAEMode_Lock = _edsdk.kEdsAEMode_Lock
kEdsAEMode_Green = _edsdk.kEdsAEMode_Green
kEdsAEMode_NightPortrait = _edsdk.kEdsAEMode_NightPortrait
kEdsAEMode_Sports = _edsdk.kEdsAEMode_Sports
kEdsAEMode_Portrait = _edsdk.kEdsAEMode_Portrait
kEdsAEMode_Landscape = _edsdk.kEdsAEMode_Landscape
kEdsAEMode_Closeup = _edsdk.kEdsAEMode_Closeup
kEdsAEMode_FlashOff = _edsdk.kEdsAEMode_FlashOff
kEdsAEMode_CreativeAuto = _edsdk.kEdsAEMode_CreativeAuto
kEdsAEMode_Movie = _edsdk.kEdsAEMode_Movie
kEdsAEMode_PhotoInMovie = _edsdk.kEdsAEMode_PhotoInMovie
kEdsAEMode_SceneIntelligentAuto = _edsdk.kEdsAEMode_SceneIntelligentAuto
kEdsAEMode_SCN = _edsdk.kEdsAEMode_SCN
kEdsAEMode_NightScenes = _edsdk.kEdsAEMode_NightScenes
kEdsAEMode_BacklitScenes = _edsdk.kEdsAEMode_BacklitScenes
kEdsAEMode_Children = _edsdk.kEdsAEMode_Children
kEdsAEMode_Food = _edsdk.kEdsAEMode_Food
kEdsAEMode_CandlelightPortraits = _edsdk.kEdsAEMode_CandlelightPortraits
kEdsAEMode_CreativeFilter = _edsdk.kEdsAEMode_CreativeFilter
kEdsAEMode_RoughMonoChrome = _edsdk.kEdsAEMode_RoughMonoChrome
kEdsAEMode_SoftFocus = _edsdk.kEdsAEMode_SoftFocus
kEdsAEMode_ToyCamera = _edsdk.kEdsAEMode_ToyCamera
kEdsAEMode_Fisheye = _edsdk.kEdsAEMode_Fisheye
kEdsAEMode_WaterColor = _edsdk.kEdsAEMode_WaterColor
kEdsAEMode_Miniature = _edsdk.kEdsAEMode_Miniature
kEdsAEMode_Hdr_Standard = _edsdk.kEdsAEMode_Hdr_Standard
kEdsAEMode_Hdr_Vivid = _edsdk.kEdsAEMode_Hdr_Vivid
kEdsAEMode_Hdr_Bold = _edsdk.kEdsAEMode_Hdr_Bold
kEdsAEMode_Hdr_Embossed = _edsdk.kEdsAEMode_Hdr_Embossed
kEdsAEMode_Movie_Fantasy = _edsdk.kEdsAEMode_Movie_Fantasy
kEdsAEMode_Movie_Old = _edsdk.kEdsAEMode_Movie_Old
kEdsAEMode_Movie_Memory = _edsdk.kEdsAEMode_Movie_Memory
kEdsAEMode_Movie_DirectMono = _edsdk.kEdsAEMode_Movie_DirectMono
kEdsAEMode_Movie_Mini = _edsdk.kEdsAEMode_Movie_Mini
kEdsAEMode_PanningAssist = _edsdk.kEdsAEMode_PanningAssist
kEdsAEMode_GroupPhoto = _edsdk.kEdsAEMode_GroupPhoto
kEdsAEMode_Myself = _edsdk.kEdsAEMode_Myself
kEdsAEMode_PlusMovieAuto = _edsdk.kEdsAEMode_PlusMovieAuto
kEdsAEMode_SmoothSkin = _edsdk.kEdsAEMode_SmoothSkin
kEdsAEMode_Panorama = _edsdk.kEdsAEMode_Panorama
kEdsAEMode_Silent = _edsdk.kEdsAEMode_Silent
kEdsAEMode_Flexible = _edsdk.kEdsAEMode_Flexible
kEdsAEMode_OilPainting = _edsdk.kEdsAEMode_OilPainting
kEdsAEMode_Fireworks = _edsdk.kEdsAEMode_Fireworks
kEdsAEMode_StarPortrait = _edsdk.kEdsAEMode_StarPortrait
kEdsAEMode_StarNightscape = _edsdk.kEdsAEMode_StarNightscape
kEdsAEMode_StarTrails = _edsdk.kEdsAEMode_StarTrails
kEdsAEMode_StarTimelapseMovie = _edsdk.kEdsAEMode_StarTimelapseMovie
kEdsAEMode_BackgroundBlur = _edsdk.kEdsAEMode_BackgroundBlur
kEdsAEMode_VideoBlog = _edsdk.kEdsAEMode_VideoBlog
kEdsAEMode_Unknown = _edsdk.kEdsAEMode_Unknown
kEdsBracket_AEB = _edsdk.kEdsBracket_AEB
kEdsBracket_ISOB = _edsdk.kEdsBracket_ISOB
kEdsBracket_WBB = _edsdk.kEdsBracket_WBB
kEdsBracket_FEB = _edsdk.kEdsBracket_FEB
kEdsBracket_Unknown = _edsdk.kEdsBracket_Unknown
kEdsEvfOutputDevice_TFT = _edsdk.kEdsEvfOutputDevice_TFT
kEdsEvfOutputDevice_PC = _edsdk.kEdsEvfOutputDevice_PC
kEdsEvfOutputDevice_PC_Small = _edsdk.kEdsEvfOutputDevice_PC_Small
kEdsEvfZoom_Fit = _edsdk.kEdsEvfZoom_Fit
kEdsEvfZoom_x5 = _edsdk.kEdsEvfZoom_x5
kEdsEvfZoom_x6 = _edsdk.kEdsEvfZoom_x6
kEdsEvfZoom_x10 = _edsdk.kEdsEvfZoom_x10
kEdsEvfZoom_x15 = _edsdk.kEdsEvfZoom_x15
Evf_AFMode_Quick = _edsdk.Evf_AFMode_Quick
Evf_AFMode_Live = _edsdk.Evf_AFMode_Live
Evf_AFMode_LiveFace = _edsdk.Evf_AFMode_LiveFace
Evf_AFMode_LiveMulti = _edsdk.Evf_AFMode_LiveMulti
Evf_AFMode_LiveZone = _edsdk.Evf_AFMode_LiveZone
Evf_AFMode_LiveSingleExpandCross = _edsdk.Evf_AFMode_LiveSingleExpandCross
Evf_AFMode_LiveSingleExpandAround = _edsdk.Evf_AFMode_LiveSingleExpandAround
Evf_AFMode_LiveZoneLargeH = _edsdk.Evf_AFMode_LiveZoneLargeH
Evf_AFMode_LiveZoneLargeV = _edsdk.Evf_AFMode_LiveZoneLargeV
Evf_AFMode_LiveCatchAF = _edsdk.Evf_AFMode_LiveCatchAF
Evf_AFMode_LiveSpotAF = _edsdk.Evf_AFMode_LiveSpotAF
Evf_AFMode_FlexibleZone1 = _edsdk.Evf_AFMode_FlexibleZone1
Evf_AFMode_FlexibleZone2 = _edsdk.Evf_AFMode_FlexibleZone2
Evf_AFMode_FlexibleZone3 = _edsdk.Evf_AFMode_FlexibleZone3
Evf_AFMode_WholeArea = _edsdk.Evf_AFMode_WholeArea
Evf_AFMode_NoTraking_Spot = _edsdk.Evf_AFMode_NoTraking_Spot
Evf_AFMode_NoTraking_1Point = _edsdk.Evf_AFMode_NoTraking_1Point
Evf_AFMode_NoTraking_ExpandCross = _edsdk.Evf_AFMode_NoTraking_ExpandCross
Evf_AFMode_NoTraking_ExpandAround = _edsdk.Evf_AFMode_NoTraking_ExpandAround
kEdsStroboModeInternal = _edsdk.kEdsStroboModeInternal
kEdsStroboModeExternalETTL = _edsdk.kEdsStroboModeExternalETTL
kEdsStroboModeExternalATTL = _edsdk.kEdsStroboModeExternalATTL
kEdsStroboModeExternalTTL = _edsdk.kEdsStroboModeExternalTTL
kEdsStroboModeExternalAuto = _edsdk.kEdsStroboModeExternalAuto
kEdsStroboModeExternalManual = _edsdk.kEdsStroboModeExternalManual
kEdsStroboModeManual = _edsdk.kEdsStroboModeManual
kEdsETTL2ModeEvaluative = _edsdk.kEdsETTL2ModeEvaluative
kEdsETTL2ModeAverage = _edsdk.kEdsETTL2ModeAverage
kEdsDcStrobeAuto = _edsdk.kEdsDcStrobeAuto
kEdsDcStrobeOn = _edsdk.kEdsDcStrobeOn
kEdsDcStrobeSlowsynchro = _edsdk.kEdsDcStrobeSlowsynchro
kEdsDcStrobeOff = _edsdk.kEdsDcStrobeOff
kDcLensBarrelStateInner = _edsdk.kDcLensBarrelStateInner
kDcLensBarrelStateOuter = _edsdk.kDcLensBarrelStateOuter
kDcRemoteShootingModeStop = _edsdk.kDcRemoteShootingModeStop
kDcRemoteShootingModeStart = _edsdk.kDcRemoteShootingModeStart
kEdsMirrorLockupStateDisable = _edsdk.kEdsMirrorLockupStateDisable
kEdsMirrorLockupStateEnable = _edsdk.kEdsMirrorLockupStateEnable
kEdsMirrorLockupStateDuringShooting = _edsdk.kEdsMirrorLockupStateDuringShooting
kEdsMirrorUpSettingOff = _edsdk.kEdsMirrorUpSettingOff
kEdsMirrorUpSettingOn = _edsdk.kEdsMirrorUpSettingOn
class EdsPoint(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_edsdk.EdsPoint_x_get, _edsdk.EdsPoint_x_set)
    y = property(_edsdk.EdsPoint_y_get, _edsdk.EdsPoint_y_set)

    def __init__(self):
        _edsdk.EdsPoint_swiginit(self, _edsdk.new_EdsPoint())
    __swig_destroy__ = _edsdk.delete_EdsPoint

# Register EdsPoint in _edsdk:
_edsdk.EdsPoint_swigregister(EdsPoint)
class EdsSize(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    width = property(_edsdk.EdsSize_width_get, _edsdk.EdsSize_width_set)
    height = property(_edsdk.EdsSize_height_get, _edsdk.EdsSize_height_set)

    def __init__(self):
        _edsdk.EdsSize_swiginit(self, _edsdk.new_EdsSize())
    __swig_destroy__ = _edsdk.delete_EdsSize

# Register EdsSize in _edsdk:
_edsdk.EdsSize_swigregister(EdsSize)
class EdsRect(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    point = property(_edsdk.EdsRect_point_get, _edsdk.EdsRect_point_set)
    size = property(_edsdk.EdsRect_size_get, _edsdk.EdsRect_size_set)

    def __init__(self):
        _edsdk.EdsRect_swiginit(self, _edsdk.new_EdsRect())
    __swig_destroy__ = _edsdk.delete_EdsRect

# Register EdsRect in _edsdk:
_edsdk.EdsRect_swigregister(EdsRect)
class EdsRational(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    numerator = property(_edsdk.EdsRational_numerator_get, _edsdk.EdsRational_numerator_set)
    denominator = property(_edsdk.EdsRational_denominator_get, _edsdk.EdsRational_denominator_set)

    def __init__(self):
        _edsdk.EdsRational_swiginit(self, _edsdk.new_EdsRational())
    __swig_destroy__ = _edsdk.delete_EdsRational

# Register EdsRational in _edsdk:
_edsdk.EdsRational_swigregister(EdsRational)
class EdsTime(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    year = property(_edsdk.EdsTime_year_get, _edsdk.EdsTime_year_set)
    month = property(_edsdk.EdsTime_month_get, _edsdk.EdsTime_month_set)
    day = property(_edsdk.EdsTime_day_get, _edsdk.EdsTime_day_set)
    hour = property(_edsdk.EdsTime_hour_get, _edsdk.EdsTime_hour_set)
    minute = property(_edsdk.EdsTime_minute_get, _edsdk.EdsTime_minute_set)
    second = property(_edsdk.EdsTime_second_get, _edsdk.EdsTime_second_set)
    milliseconds = property(_edsdk.EdsTime_milliseconds_get, _edsdk.EdsTime_milliseconds_set)

    def __init__(self):
        _edsdk.EdsTime_swiginit(self, _edsdk.new_EdsTime())
    __swig_destroy__ = _edsdk.delete_EdsTime

# Register EdsTime in _edsdk:
_edsdk.EdsTime_swigregister(EdsTime)
class EdsGpsMetaData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    latitudeRef = property(_edsdk.EdsGpsMetaData_latitudeRef_get, _edsdk.EdsGpsMetaData_latitudeRef_set)
    longitudeRef = property(_edsdk.EdsGpsMetaData_longitudeRef_get, _edsdk.EdsGpsMetaData_longitudeRef_set)
    altitudeRef = property(_edsdk.EdsGpsMetaData_altitudeRef_get, _edsdk.EdsGpsMetaData_altitudeRef_set)
    status = property(_edsdk.EdsGpsMetaData_status_get, _edsdk.EdsGpsMetaData_status_set)
    latitude = property(_edsdk.EdsGpsMetaData_latitude_get, _edsdk.EdsGpsMetaData_latitude_set)
    longitude = property(_edsdk.EdsGpsMetaData_longitude_get, _edsdk.EdsGpsMetaData_longitude_set)
    altitude = property(_edsdk.EdsGpsMetaData_altitude_get, _edsdk.EdsGpsMetaData_altitude_set)
    timeStamp = property(_edsdk.EdsGpsMetaData_timeStamp_get, _edsdk.EdsGpsMetaData_timeStamp_set)
    dateStampYear = property(_edsdk.EdsGpsMetaData_dateStampYear_get, _edsdk.EdsGpsMetaData_dateStampYear_set)
    dateStampMonth = property(_edsdk.EdsGpsMetaData_dateStampMonth_get, _edsdk.EdsGpsMetaData_dateStampMonth_set)
    dateStampDay = property(_edsdk.EdsGpsMetaData_dateStampDay_get, _edsdk.EdsGpsMetaData_dateStampDay_set)

    def __init__(self):
        _edsdk.EdsGpsMetaData_swiginit(self, _edsdk.new_EdsGpsMetaData())
    __swig_destroy__ = _edsdk.delete_EdsGpsMetaData

# Register EdsGpsMetaData in _edsdk:
_edsdk.EdsGpsMetaData_swigregister(EdsGpsMetaData)
class EdsDeviceInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    szPortName = property(_edsdk.EdsDeviceInfo_szPortName_get, _edsdk.EdsDeviceInfo_szPortName_set)
    szDeviceDescription = property(_edsdk.EdsDeviceInfo_szDeviceDescription_get, _edsdk.EdsDeviceInfo_szDeviceDescription_set)
    deviceSubType = property(_edsdk.EdsDeviceInfo_deviceSubType_get, _edsdk.EdsDeviceInfo_deviceSubType_set)
    reserved = property(_edsdk.EdsDeviceInfo_reserved_get, _edsdk.EdsDeviceInfo_reserved_set)

    def __init__(self):
        _edsdk.EdsDeviceInfo_swiginit(self, _edsdk.new_EdsDeviceInfo())
    __swig_destroy__ = _edsdk.delete_EdsDeviceInfo

# Register EdsDeviceInfo in _edsdk:
_edsdk.EdsDeviceInfo_swigregister(EdsDeviceInfo)
class EdsVolumeInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    storageType = property(_edsdk.EdsVolumeInfo_storageType_get, _edsdk.EdsVolumeInfo_storageType_set)
    access = property(_edsdk.EdsVolumeInfo_access_get, _edsdk.EdsVolumeInfo_access_set)
    maxCapacity = property(_edsdk.EdsVolumeInfo_maxCapacity_get, _edsdk.EdsVolumeInfo_maxCapacity_set)
    freeSpaceInBytes = property(_edsdk.EdsVolumeInfo_freeSpaceInBytes_get, _edsdk.EdsVolumeInfo_freeSpaceInBytes_set)
    szVolumeLabel = property(_edsdk.EdsVolumeInfo_szVolumeLabel_get, _edsdk.EdsVolumeInfo_szVolumeLabel_set)

    def __init__(self):
        _edsdk.EdsVolumeInfo_swiginit(self, _edsdk.new_EdsVolumeInfo())
    __swig_destroy__ = _edsdk.delete_EdsVolumeInfo

# Register EdsVolumeInfo in _edsdk:
_edsdk.EdsVolumeInfo_swigregister(EdsVolumeInfo)
class EdsDirectoryItemInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    size = property(_edsdk.EdsDirectoryItemInfo_size_get, _edsdk.EdsDirectoryItemInfo_size_set)
    isFolder = property(_edsdk.EdsDirectoryItemInfo_isFolder_get, _edsdk.EdsDirectoryItemInfo_isFolder_set)
    groupID = property(_edsdk.EdsDirectoryItemInfo_groupID_get, _edsdk.EdsDirectoryItemInfo_groupID_set)
    option = property(_edsdk.EdsDirectoryItemInfo_option_get, _edsdk.EdsDirectoryItemInfo_option_set)
    szFileName = property(_edsdk.EdsDirectoryItemInfo_szFileName_get, _edsdk.EdsDirectoryItemInfo_szFileName_set)
    format = property(_edsdk.EdsDirectoryItemInfo_format_get, _edsdk.EdsDirectoryItemInfo_format_set)
    dateTime = property(_edsdk.EdsDirectoryItemInfo_dateTime_get, _edsdk.EdsDirectoryItemInfo_dateTime_set)

    def __init__(self):
        _edsdk.EdsDirectoryItemInfo_swiginit(self, _edsdk.new_EdsDirectoryItemInfo())
    __swig_destroy__ = _edsdk.delete_EdsDirectoryItemInfo

# Register EdsDirectoryItemInfo in _edsdk:
_edsdk.EdsDirectoryItemInfo_swigregister(EdsDirectoryItemInfo)
class EdsImageInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    width = property(_edsdk.EdsImageInfo_width_get, _edsdk.EdsImageInfo_width_set)
    height = property(_edsdk.EdsImageInfo_height_get, _edsdk.EdsImageInfo_height_set)
    numOfComponents = property(_edsdk.EdsImageInfo_numOfComponents_get, _edsdk.EdsImageInfo_numOfComponents_set)
    componentDepth = property(_edsdk.EdsImageInfo_componentDepth_get, _edsdk.EdsImageInfo_componentDepth_set)
    effectiveRect = property(_edsdk.EdsImageInfo_effectiveRect_get, _edsdk.EdsImageInfo_effectiveRect_set)
    reserved1 = property(_edsdk.EdsImageInfo_reserved1_get, _edsdk.EdsImageInfo_reserved1_set)
    reserved2 = property(_edsdk.EdsImageInfo_reserved2_get, _edsdk.EdsImageInfo_reserved2_set)

    def __init__(self):
        _edsdk.EdsImageInfo_swiginit(self, _edsdk.new_EdsImageInfo())
    __swig_destroy__ = _edsdk.delete_EdsImageInfo

# Register EdsImageInfo in _edsdk:
_edsdk.EdsImageInfo_swigregister(EdsImageInfo)
class EdsSaveImageSetting(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    JPEGQuality = property(_edsdk.EdsSaveImageSetting_JPEGQuality_get, _edsdk.EdsSaveImageSetting_JPEGQuality_set)
    iccProfileStream = property(_edsdk.EdsSaveImageSetting_iccProfileStream_get, _edsdk.EdsSaveImageSetting_iccProfileStream_set)
    reserved = property(_edsdk.EdsSaveImageSetting_reserved_get, _edsdk.EdsSaveImageSetting_reserved_set)

    def __init__(self):
        _edsdk.EdsSaveImageSetting_swiginit(self, _edsdk.new_EdsSaveImageSetting())
    __swig_destroy__ = _edsdk.delete_EdsSaveImageSetting

# Register EdsSaveImageSetting in _edsdk:
_edsdk.EdsSaveImageSetting_swigregister(EdsSaveImageSetting)
class EdsPropertyDesc(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    form = property(_edsdk.EdsPropertyDesc_form_get, _edsdk.EdsPropertyDesc_form_set)
    access = property(_edsdk.EdsPropertyDesc_access_get, _edsdk.EdsPropertyDesc_access_set)
    numElements = property(_edsdk.EdsPropertyDesc_numElements_get, _edsdk.EdsPropertyDesc_numElements_set)
    propDesc = property(_edsdk.EdsPropertyDesc_propDesc_get, _edsdk.EdsPropertyDesc_propDesc_set)

    def __init__(self):
        _edsdk.EdsPropertyDesc_swiginit(self, _edsdk.new_EdsPropertyDesc())
    __swig_destroy__ = _edsdk.delete_EdsPropertyDesc

# Register EdsPropertyDesc in _edsdk:
_edsdk.EdsPropertyDesc_swigregister(EdsPropertyDesc)
class EdsPictureStyleDesc(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    contrast = property(_edsdk.EdsPictureStyleDesc_contrast_get, _edsdk.EdsPictureStyleDesc_contrast_set)
    sharpness = property(_edsdk.EdsPictureStyleDesc_sharpness_get, _edsdk.EdsPictureStyleDesc_sharpness_set)
    saturation = property(_edsdk.EdsPictureStyleDesc_saturation_get, _edsdk.EdsPictureStyleDesc_saturation_set)
    colorTone = property(_edsdk.EdsPictureStyleDesc_colorTone_get, _edsdk.EdsPictureStyleDesc_colorTone_set)
    filterEffect = property(_edsdk.EdsPictureStyleDesc_filterEffect_get, _edsdk.EdsPictureStyleDesc_filterEffect_set)
    toningEffect = property(_edsdk.EdsPictureStyleDesc_toningEffect_get, _edsdk.EdsPictureStyleDesc_toningEffect_set)
    sharpFineness = property(_edsdk.EdsPictureStyleDesc_sharpFineness_get, _edsdk.EdsPictureStyleDesc_sharpFineness_set)
    sharpThreshold = property(_edsdk.EdsPictureStyleDesc_sharpThreshold_get, _edsdk.EdsPictureStyleDesc_sharpThreshold_set)

    def __init__(self):
        _edsdk.EdsPictureStyleDesc_swiginit(self, _edsdk.new_EdsPictureStyleDesc())
    __swig_destroy__ = _edsdk.delete_EdsPictureStyleDesc

# Register EdsPictureStyleDesc in _edsdk:
_edsdk.EdsPictureStyleDesc_swigregister(EdsPictureStyleDesc)
class EdsFocusPoint(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    valid = property(_edsdk.EdsFocusPoint_valid_get, _edsdk.EdsFocusPoint_valid_set)
    selected = property(_edsdk.EdsFocusPoint_selected_get, _edsdk.EdsFocusPoint_selected_set)
    justFocus = property(_edsdk.EdsFocusPoint_justFocus_get, _edsdk.EdsFocusPoint_justFocus_set)
    rect = property(_edsdk.EdsFocusPoint_rect_get, _edsdk.EdsFocusPoint_rect_set)
    reserved = property(_edsdk.EdsFocusPoint_reserved_get, _edsdk.EdsFocusPoint_reserved_set)

    def __init__(self):
        _edsdk.EdsFocusPoint_swiginit(self, _edsdk.new_EdsFocusPoint())
    __swig_destroy__ = _edsdk.delete_EdsFocusPoint

# Register EdsFocusPoint in _edsdk:
_edsdk.EdsFocusPoint_swigregister(EdsFocusPoint)
class EdsFocusInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    imageRect = property(_edsdk.EdsFocusInfo_imageRect_get, _edsdk.EdsFocusInfo_imageRect_set)
    pointNumber = property(_edsdk.EdsFocusInfo_pointNumber_get, _edsdk.EdsFocusInfo_pointNumber_set)
    focusPoint = property(_edsdk.EdsFocusInfo_focusPoint_get, _edsdk.EdsFocusInfo_focusPoint_set)
    executeMode = property(_edsdk.EdsFocusInfo_executeMode_get, _edsdk.EdsFocusInfo_executeMode_set)

    def __init__(self):
        _edsdk.EdsFocusInfo_swiginit(self, _edsdk.new_EdsFocusInfo())
    __swig_destroy__ = _edsdk.delete_EdsFocusInfo

# Register EdsFocusInfo in _edsdk:
_edsdk.EdsFocusInfo_swigregister(EdsFocusInfo)
class EdsUsersetData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    valid = property(_edsdk.EdsUsersetData_valid_get, _edsdk.EdsUsersetData_valid_set)
    dataSize = property(_edsdk.EdsUsersetData_dataSize_get, _edsdk.EdsUsersetData_dataSize_set)
    szCaption = property(_edsdk.EdsUsersetData_szCaption_get, _edsdk.EdsUsersetData_szCaption_set)
    data = property(_edsdk.EdsUsersetData_data_get, _edsdk.EdsUsersetData_data_set)

    def __init__(self):
        _edsdk.EdsUsersetData_swiginit(self, _edsdk.new_EdsUsersetData())
    __swig_destroy__ = _edsdk.delete_EdsUsersetData

# Register EdsUsersetData in _edsdk:
_edsdk.EdsUsersetData_swigregister(EdsUsersetData)
class EdsCapacity(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    numberOfFreeClusters = property(_edsdk.EdsCapacity_numberOfFreeClusters_get, _edsdk.EdsCapacity_numberOfFreeClusters_set)
    bytesPerSector = property(_edsdk.EdsCapacity_bytesPerSector_get, _edsdk.EdsCapacity_bytesPerSector_set)
    reset = property(_edsdk.EdsCapacity_reset_get, _edsdk.EdsCapacity_reset_set)

    def __init__(self):
        _edsdk.EdsCapacity_swiginit(self, _edsdk.new_EdsCapacity())
    __swig_destroy__ = _edsdk.delete_EdsCapacity

# Register EdsCapacity in _edsdk:
_edsdk.EdsCapacity_swigregister(EdsCapacity)
class EdsFramePoint(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_edsdk.EdsFramePoint_x_get, _edsdk.EdsFramePoint_x_set)
    y = property(_edsdk.EdsFramePoint_y_get, _edsdk.EdsFramePoint_y_set)

    def __init__(self):
        _edsdk.EdsFramePoint_swiginit(self, _edsdk.new_EdsFramePoint())
    __swig_destroy__ = _edsdk.delete_EdsFramePoint

# Register EdsFramePoint in _edsdk:
_edsdk.EdsFramePoint_swigregister(EdsFramePoint)
class EdsCameraPos(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    status = property(_edsdk.EdsCameraPos_status_get, _edsdk.EdsCameraPos_status_set)
    position = property(_edsdk.EdsCameraPos_position_get, _edsdk.EdsCameraPos_position_set)
    rolling = property(_edsdk.EdsCameraPos_rolling_get, _edsdk.EdsCameraPos_rolling_set)
    pitching = property(_edsdk.EdsCameraPos_pitching_get, _edsdk.EdsCameraPos_pitching_set)

    def __init__(self):
        _edsdk.EdsCameraPos_swiginit(self, _edsdk.new_EdsCameraPos())
    __swig_destroy__ = _edsdk.delete_EdsCameraPos

# Register EdsCameraPos in _edsdk:
_edsdk.EdsCameraPos_swigregister(EdsCameraPos)
class EdsFocusShiftSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    version = property(_edsdk.EdsFocusShiftSet_version_get, _edsdk.EdsFocusShiftSet_version_set)
    focusShiftFunction = property(_edsdk.EdsFocusShiftSet_focusShiftFunction_get, _edsdk.EdsFocusShiftSet_focusShiftFunction_set)
    shootingNumber = property(_edsdk.EdsFocusShiftSet_shootingNumber_get, _edsdk.EdsFocusShiftSet_shootingNumber_set)
    stepWidth = property(_edsdk.EdsFocusShiftSet_stepWidth_get, _edsdk.EdsFocusShiftSet_stepWidth_set)
    exposureSmoothing = property(_edsdk.EdsFocusShiftSet_exposureSmoothing_get, _edsdk.EdsFocusShiftSet_exposureSmoothing_set)
    focusStackingFunction = property(_edsdk.EdsFocusShiftSet_focusStackingFunction_get, _edsdk.EdsFocusShiftSet_focusStackingFunction_set)
    focusStackingTrimming = property(_edsdk.EdsFocusShiftSet_focusStackingTrimming_get, _edsdk.EdsFocusShiftSet_focusStackingTrimming_set)
    flashInterval = property(_edsdk.EdsFocusShiftSet_flashInterval_get, _edsdk.EdsFocusShiftSet_flashInterval_set)

    def __init__(self):
        _edsdk.EdsFocusShiftSet_swiginit(self, _edsdk.new_EdsFocusShiftSet())
    __swig_destroy__ = _edsdk.delete_EdsFocusShiftSet

# Register EdsFocusShiftSet in _edsdk:
_edsdk.EdsFocusShiftSet_swigregister(EdsFocusShiftSet)
class EdsManualWBData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    valid = property(_edsdk.EdsManualWBData_valid_get, _edsdk.EdsManualWBData_valid_set)
    dataSize = property(_edsdk.EdsManualWBData_dataSize_get, _edsdk.EdsManualWBData_dataSize_set)
    szCaption = property(_edsdk.EdsManualWBData_szCaption_get, _edsdk.EdsManualWBData_szCaption_set)
    data = property(_edsdk.EdsManualWBData_data_get, _edsdk.EdsManualWBData_data_set)

    def __init__(self):
        _edsdk.EdsManualWBData_swiginit(self, _edsdk.new_EdsManualWBData())
    __swig_destroy__ = _edsdk.delete_EdsManualWBData

# Register EdsManualWBData in _edsdk:
_edsdk.EdsManualWBData_swigregister(EdsManualWBData)
class ApertureLockSetting(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    apertureLockStatus = property(_edsdk.ApertureLockSetting_apertureLockStatus_get, _edsdk.ApertureLockSetting_apertureLockStatus_set)
    avValue = property(_edsdk.ApertureLockSetting_avValue_get, _edsdk.ApertureLockSetting_avValue_set)

    def __init__(self):
        _edsdk.ApertureLockSetting_swiginit(self, _edsdk.new_ApertureLockSetting())
    __swig_destroy__ = _edsdk.delete_ApertureLockSetting

# Register ApertureLockSetting in _edsdk:
_edsdk.ApertureLockSetting_swigregister(ApertureLockSetting)
class EdsIStream(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    context = property(_edsdk.EdsIStream_context_get, _edsdk.EdsIStream_context_set)
    read = property(_edsdk.EdsIStream_read_get, _edsdk.EdsIStream_read_set)
    write = property(_edsdk.EdsIStream_write_get, _edsdk.EdsIStream_write_set)
    seek = property(_edsdk.EdsIStream_seek_get, _edsdk.EdsIStream_seek_set)
    tell = property(_edsdk.EdsIStream_tell_get, _edsdk.EdsIStream_tell_set)
    getLength = property(_edsdk.EdsIStream_getLength_get, _edsdk.EdsIStream_getLength_set)

    def __init__(self):
        _edsdk.EdsIStream_swiginit(self, _edsdk.new_EdsIStream())
    __swig_destroy__ = _edsdk.delete_EdsIStream

# Register EdsIStream in _edsdk:
_edsdk.EdsIStream_swigregister(EdsIStream)

def EdsInitializeSDK():
    return _edsdk.EdsInitializeSDK()

def EdsTerminateSDK():
    return _edsdk.EdsTerminateSDK()

def EdsRetain(inRef):
    return _edsdk.EdsRetain(inRef)

def EdsRelease(inRef):
    return _edsdk.EdsRelease(inRef)

def EdsGetChildCount(inRef, outCount):
    return _edsdk.EdsGetChildCount(inRef, outCount)

def EdsGetChildAtIndex(inRef, inIndex, outRef):
    return _edsdk.EdsGetChildAtIndex(inRef, inIndex, outRef)

def EdsGetParent(inRef, outParentRef):
    return _edsdk.EdsGetParent(inRef, outParentRef)

def EdsGetPropertySize(inRef, inPropertyID, inParam, outDataType, outSize):
    return _edsdk.EdsGetPropertySize(inRef, inPropertyID, inParam, outDataType, outSize)

def EdsGetPropertyData(inRef, inPropertyID, inParam, inPropertySize, outPropertyData):
    return _edsdk.EdsGetPropertyData(inRef, inPropertyID, inParam, inPropertySize, outPropertyData)

def EdsSetPropertyData(inRef, inPropertyID, inParam, inPropertySize, inPropertyData):
    return _edsdk.EdsSetPropertyData(inRef, inPropertyID, inParam, inPropertySize, inPropertyData)

def EdsGetPropertyDesc(inRef, inPropertyID, outPropertyDesc):
    return _edsdk.EdsGetPropertyDesc(inRef, inPropertyID, outPropertyDesc)

def EdsGetCameraList(outCameraListRef):
    return _edsdk.EdsGetCameraList(outCameraListRef)

def EdsGetDeviceInfo(inCameraRef, outDeviceInfo):
    return _edsdk.EdsGetDeviceInfo(inCameraRef, outDeviceInfo)

def EdsOpenSession(inCameraRef):
    return _edsdk.EdsOpenSession(inCameraRef)

def EdsCloseSession(inCameraRef):
    return _edsdk.EdsCloseSession(inCameraRef)

def EdsSendCommand(inCameraRef, inCommand, inParam):
    return _edsdk.EdsSendCommand(inCameraRef, inCommand, inParam)

def EdsSendStatusCommand(inCameraRef, inStatusCommand, inParam):
    return _edsdk.EdsSendStatusCommand(inCameraRef, inStatusCommand, inParam)

def EdsSetCapacity(inCameraRef, inCapacity):
    return _edsdk.EdsSetCapacity(inCameraRef, inCapacity)

def EdsGetVolumeInfo(inVolumeRef, outVolumeInfo):
    return _edsdk.EdsGetVolumeInfo(inVolumeRef, outVolumeInfo)

def EdsFormatVolume(inVolumeRef):
    return _edsdk.EdsFormatVolume(inVolumeRef)

def EdsGetDirectoryItemInfo(inDirItemRef, outDirItemInfo):
    return _edsdk.EdsGetDirectoryItemInfo(inDirItemRef, outDirItemInfo)

def EdsDeleteDirectoryItem(inDirItemRef):
    return _edsdk.EdsDeleteDirectoryItem(inDirItemRef)

def EdsDownload(inDirItemRef, inReadSize, outStream):
    return _edsdk.EdsDownload(inDirItemRef, inReadSize, outStream)

def EdsDownloadCancel(inDirItemRef):
    return _edsdk.EdsDownloadCancel(inDirItemRef)

def EdsDownloadComplete(inDirItemRef):
    return _edsdk.EdsDownloadComplete(inDirItemRef)

def EdsDownloadThumbnail(inDirItemRef, outStream):
    return _edsdk.EdsDownloadThumbnail(inDirItemRef, outStream)

def EdsGetAttribute(inDirItemRef, outFileAttribute):
    return _edsdk.EdsGetAttribute(inDirItemRef, outFileAttribute)

def EdsSetAttribute(inDirItemRef, inFileAttribute):
    return _edsdk.EdsSetAttribute(inDirItemRef, inFileAttribute)

def EdsSetMetaImage(inDirItemRef, inMetaType, inMetaDataSize, inMetaData):
    return _edsdk.EdsSetMetaImage(inDirItemRef, inMetaType, inMetaDataSize, inMetaData)

def EdsCreateFileStream(inFileName, inCreateDisposition, inDesiredAccess, outStream):
    return _edsdk.EdsCreateFileStream(inFileName, inCreateDisposition, inDesiredAccess, outStream)

def EdsCreateMemoryStream(inBufferSize, outStream):
    return _edsdk.EdsCreateMemoryStream(inBufferSize, outStream)

def EdsCreateFileStreamEx(inFileName, inCreateDisposition, inDesiredAccess, outStream):
    return _edsdk.EdsCreateFileStreamEx(inFileName, inCreateDisposition, inDesiredAccess, outStream)

def EdsCreateMemoryStreamFromPointer(inUserBuffer, inBufferSize, outStream):
    return _edsdk.EdsCreateMemoryStreamFromPointer(inUserBuffer, inBufferSize, outStream)

def EdsGetPointer(inStream, outPointer):
    return _edsdk.EdsGetPointer(inStream, outPointer)

def EdsRead(inStreamRef, inReadSize, outBuffer, outReadSize):
    return _edsdk.EdsRead(inStreamRef, inReadSize, outBuffer, outReadSize)

def EdsWrite(inStreamRef, inWriteSize, inBuffer, outWrittenSize):
    return _edsdk.EdsWrite(inStreamRef, inWriteSize, inBuffer, outWrittenSize)

def EdsSeek(inStreamRef, inSeekOffset, inSeekOrigin):
    return _edsdk.EdsSeek(inStreamRef, inSeekOffset, inSeekOrigin)

def EdsGetPosition(inStreamRef, outPosition):
    return _edsdk.EdsGetPosition(inStreamRef, outPosition)

def EdsGetLength(inStreamRef, outLength):
    return _edsdk.EdsGetLength(inStreamRef, outLength)

def EdsCopyData(inStreamRef, inWriteSize, outStreamRef):
    return _edsdk.EdsCopyData(inStreamRef, inWriteSize, outStreamRef)

def EdsSetProgressCallback(inRef, inProgressCallback, inProgressOption, inContext):
    return _edsdk.EdsSetProgressCallback(inRef, inProgressCallback, inProgressOption, inContext)

def EdsCreateImageRef(inStreamRef, outImageRef):
    return _edsdk.EdsCreateImageRef(inStreamRef, outImageRef)

def EdsGetImageInfo(inImageRef, inImageSource, outImageInfo):
    return _edsdk.EdsGetImageInfo(inImageRef, inImageSource, outImageInfo)

def EdsGetImage(inImageRef, inImageSource, inImageType, inSrcRect, inDstSize, outStreamRef):
    return _edsdk.EdsGetImage(inImageRef, inImageSource, inImageType, inSrcRect, inDstSize, outStreamRef)

def EdsCreateEvfImageRef(inStreamRef, outEvfImageRef):
    return _edsdk.EdsCreateEvfImageRef(inStreamRef, outEvfImageRef)

def EdsDownloadEvfImage(inCameraRef, inEvfImageRef):
    return _edsdk.EdsDownloadEvfImage(inCameraRef, inEvfImageRef)

def EdsSetCameraAddedHandler(inCameraAddedHandler, inContext):
    return _edsdk.EdsSetCameraAddedHandler(inCameraAddedHandler, inContext)

def EdsSetPropertyEventHandler(inCameraRef, inEvnet, inPropertyEventHandler, inContext):
    return _edsdk.EdsSetPropertyEventHandler(inCameraRef, inEvnet, inPropertyEventHandler, inContext)

def EdsSetObjectEventHandler(inCameraRef, inEvnet, inObjectEventHandler, inContext):
    return _edsdk.EdsSetObjectEventHandler(inCameraRef, inEvnet, inObjectEventHandler, inContext)

def EdsSetCameraStateEventHandler(inCameraRef, inEvnet, inStateEventHandler, inContext):
    return _edsdk.EdsSetCameraStateEventHandler(inCameraRef, inEvnet, inStateEventHandler, inContext)

def EdsCreateStream(inStream, outStreamRef):
    return _edsdk.EdsCreateStream(inStream, outStreamRef)

def EdsGetEvent():
    return _edsdk.EdsGetEvent()

def EdsSetFramePoint(inCameraRef, inFramepoint, inLockAfFrame):
    return _edsdk.EdsSetFramePoint(inCameraRef, inFramepoint, inLockAfFrame)

